name: scrollable_inertia
description: Customizable scrollable's animations to make your app stand out from the crowd.
version: 0.0.1
homepage: https://wrbl.xyz
repository: https://github.com/wrbl606/inertia
topics:
  - flutter
  - implicit-animation
  - widgets
  - scrollable
screenshots:
  - description: 'Motion blur demo'
    path: asset/blur.webp
  - description: 'Interia-based spacing demo'
    path: asset/spacing.webp

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mockito: ^5.3.2
  lints: ^2.1.1
